//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilioSMSTestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSRecord
    {
        public int ID { get; set; }
        public string vchMessageIn { get; set; }
        public string vchMessageOut { get; set; }
        public Nullable<System.DateTime> dttmTimeStamp { get; set; }
    }
}
